spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://kosa2.iptime.org:50332/finalproject
    username: admin
    password: 1234
  mvc.pathmatch.matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: com.example.final_project.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-executor-type: reuse

jwt :
  secret : douzoneFinalTeam1SecretMessageForJWT
  token.validation :
    access : 86400
    refresh : 1296000

cloud:
  aws:
    stack.auto : false
    s3.bucket: dzfinal
    region.static : ap-northeast-2
    credentials :
      accessKey : AKIAQQ3ZNZATO5RUOANM
      secretKey : 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
